spring:
  profiles:
    active: development
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 1800
      cookie:
        name: SS_SHOWCASE

---
spring:
  profiles: development
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: RD_SHOWCASE
  redis:
    host: localhost
    port: 6379
    database: 6
    timeout: 5000

server:
  port: 8082
  servlet:
    context-path: /showcase

security:
  oauth2:
    client:
      client-id: sub_showcase
      client-secret: '123456'
      access-token-uri: http://localhost:8080/authen/oauth/token
      user-authorization-uri: http://localhost:8080/authen/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/authen/user/me

