spring:
  profiles:
    active: development
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 1800
      cookie:
        name: SS_AUTHEN

---
spring:
  profiles: development
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: RD_AUTHEN
  redis:
    host: localhost
    port: 6379
    database: 4
    timeout: 5000

server:
  port: 8080
  servlet:
    context-path: /authen
